config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'
  resources :contacts do
    resources :phone_numbers
  end
  resource :tags, only: [:create]
  get '/search', to: 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 200 }
  has_many :phone_numbers, -> { includes :tag }, dependent: :delete_all

  def self.search(query)
    left_outer_joins(:phone_numbers)
        .where('contacts.name ILIKE :query OR phone_numbers.number ILIKE :query', query: "%#{query}%").distinct
  end
end

app/models/phone_number.rb
# == Schema Information
#
# Table name: phone_numbers
#
#  id         :bigint(8)        not null, primary key
#  number     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  contact_id :bigint(8)
#  tag_id     :bigint(8)
#
# Indexes
#
#  index_phone_numbers_on_contact_id  (contact_id)
#  index_phone_numbers_on_tag_id      (tag_id)
#
# Foreign Keys
#
#  fk_rails_...  (contact_id => contacts.id)
#  fk_rails_...  (tag_id => tags.id)
#

class PhoneNumber < ApplicationRecord
  PHONE_FORMAT = /\A\+\d{12}\z/
  validates :number,
            presence: true,
            format: { with: PHONE_FORMAT,
                      message: 'invalid format.' }

  belongs_to :contact
  belongs_to :tag

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  predefined :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_tags_on_name  (name) UNIQUE
#

class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
    @phone_number = PhoneNumber.new(contact: @contact)
    @select_tags = Tag.pluck(:name, :id) << ['Create custom', -1]
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact, notice: 'Contact successfully created!'
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(contact_params)
      redirect_to @contact, notice: 'Contact successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.json { render json: { contact_id: @contact.id } }
      format.html { redirect_to contacts_path }
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name)
  end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController

  def destroy
    @phone_number = PhoneNumber.find(params[:id])
    @phone_number.destroy
    render json: { phone_id: @phone_number.id }
  end

  def create
    @phone_number = PhoneNumber.new(phone_number_params)
    @phone_number.contact_id = params[:contact_id]
    if @phone_number.save
      phone_html = render_to_string(template: 'phone_numbers/_phone_number',
                                    layout: false,
                                    locals: { phone_number: @phone_number })
      render json: { phone: phone_html }
    else
      error_msg = 'Phone number ' + @phone_number.errors.messages[:number].first
      flash.now[:notice] = error_msg
      render json: { error: error_msg }, status: :bad_request
    end
  end

  private

  def phone_number_params
    params.require(:phone_number).permit(:number, :tag_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    render json: Contact.search(params[:query]).pluck(:id).map(&:to_s)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    @tag = Tag.new(tag_params)
    @tag.predefined = false
    render json: { tag: @tag } if @tag.save
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/contacts/_contact.html.erb
<div class="contact text-center searchable" id="contact_<%= contact.id %>" data-contact-id="<%= contact.id %>">
  <hr>
  <%= fa_icon 'user' %>
  <%= link_to contact.name, contact_path(contact), class: 'ml-2' %>
  <%= link_to contact_path(contact), method: :delete, class: 'delete_contact ml-2',
              remote: true,
              data: { contact_id: contact.id, confirm: "Delete #{contact.name}?" } do %>
    <%= fa_icon 'trash' %>
  <% end %>
  <hr>
</div>

app/views/contacts/_form.html.erb
<div class="col-lg-6 offset-lg-3">
  <%= simple_form_for @contact do |f| %>
    <%= f.input :name, required: true, autofocus: true, value: @contact.name %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<h2>Edit contact name</h2>
<%= render 'contacts/form' %>

app/views/contacts/index.html.erb
<h1 class="text-center">Contacts</h1>
<div class="col-lg-4 offset-lg-4">
  <form class="form-inline my-2 my-lg-0" id="search_form">
    <input class="form-control mr-sm-2" id="search_query" type="search" placeholder="Search" aria-label="Search" name="query">
  </form>
</div>
<%= render @contacts %>

app/views/contacts/new.html.erb
<h1>New contact</h1>
<%= render 'contacts/form' %>

app/views/contacts/show.html.erb
<div id="contact_<%= @contact.id %>" class="contact">
  <h1 class="text-center"><%= @contact.name %></h1>
  <div class="contact_controls text-center">
    <%= link_to 'Edit name', edit_contact_path(@contact) %> |
    <%= link_to 'Delete', @contact,
                method: :delete,
                data: { confirm: "Delete #{@contact.name}?" } %>
  </div>
  <hr>
  <h3 class="text-center">Phone numbers</h3>
  <hr>
  <div class="contacts text-center" id="phones">
    <%= render partial: 'phone_numbers/phone_number', collection: @contact.phone_numbers %>
  </div>
  <hr>
  <div class="phone_form col-lg-6 offset-lg-3">
    <%= render 'phone_numbers/form' %>
    <%= render 'tags/modal_form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConstactsApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<style>
  #search_form {
    margin-left: 23%;
  }
</style>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Contacts Book</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Contacts', contacts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Add contact', new_contact_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>
<% if flash[:notice] %>
  <div class="alert alert-dismissible alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/phone_numbers/_form.html.erb
<%= simple_form_for @phone_number, url: contact_phone_numbers_path(@contact), method: :post, remote: true, html: { class: 'form-inline' } do |f| %>
  <%= f.input :tag_id, as: :select, collection: @select_tags, include_blank: false %>
  <%= f.input :number, required: true, autofocus: true,
              value: @phone_number.number %>
  <%= f.submit value: 'Add number', class: 'btn btn-primary ml-2' %>
<% end %>

app/views/phone_numbers/_phone_number.html.erb
<div class="phone" id="phone_<%= phone_number.id %>">
  <%= phone_number.tag.name %> : <%= phone_number.number %>
  <%= link_to 'Delete', contact_phone_number_path(phone_number.contact.id, phone_number),
              remote: true, method: :delete, class: 'delete_phone',
              data: { confirm: "Delete #{phone_number.number}?" } %>
</div>

app/views/tags/_modal_form.html.erb
<div class="modal fade" id="tag_modal_form" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <%= simple_form_for Tag.new, html: { class: 'inline-form' }, remote: true do |f| %>
        <%= f.input :name, required: true, autofocus: true %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>